# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
