# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_likes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes',
        ),
    ]
